# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Slalo\Dropbox\PythonScripts\VTM\VTMConfig05.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_dialogConfig(object):
    def setupUi(self, dialogConfig):
        dialogConfig.setObjectName("dialogConfig")
        dialogConfig.setEnabled(True)
        dialogConfig.resize(983, 788)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("VTMIconSmall.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        dialogConfig.setWindowIcon(icon)
        self.buttonBox = QtWidgets.QDialogButtonBox(dialogConfig)
        self.buttonBox.setGeometry(QtCore.QRect(730, 740, 221, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.grpboxJumpColors = QtWidgets.QGroupBox(dialogConfig)
        self.grpboxJumpColors.setGeometry(QtCore.QRect(30, 200, 201, 161))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.grpboxJumpColors.setFont(font)
        self.grpboxJumpColors.setObjectName("grpboxJumpColors")
        self.radbtnJumpRed = QtWidgets.QRadioButton(self.grpboxJumpColors)
        self.radbtnJumpRed.setGeometry(QtCore.QRect(10, 40, 191, 20))
        self.radbtnJumpRed.setChecked(True)
        self.radbtnJumpRed.setObjectName("radbtnJumpRed")
        self.radbtnJumpBlack = QtWidgets.QRadioButton(self.grpboxJumpColors)
        self.radbtnJumpBlack.setGeometry(QtCore.QRect(10, 70, 181, 20))
        self.radbtnJumpBlack.setObjectName("radbtnJumpBlack")
        self.radbtnJumpYellow = QtWidgets.QRadioButton(self.grpboxJumpColors)
        self.radbtnJumpYellow.setGeometry(QtCore.QRect(10, 100, 181, 20))
        self.radbtnJumpYellow.setObjectName("radbtnJumpYellow")
        self.radbtnJumpGreen = QtWidgets.QRadioButton(self.grpboxJumpColors)
        self.radbtnJumpGreen.setGeometry(QtCore.QRect(10, 130, 95, 20))
        self.radbtnJumpGreen.setObjectName("radbtnJumpGreen")
        self.grpboxGridColors = QtWidgets.QGroupBox(dialogConfig)
        self.grpboxGridColors.setGeometry(QtCore.QRect(30, 380, 201, 161))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.grpboxGridColors.setFont(font)
        self.grpboxGridColors.setObjectName("grpboxGridColors")
        self.radbtnGridRed = QtWidgets.QRadioButton(self.grpboxGridColors)
        self.radbtnGridRed.setGeometry(QtCore.QRect(20, 40, 111, 20))
        self.radbtnGridRed.setObjectName("radbtnGridRed")
        self.radbtnGridBlack = QtWidgets.QRadioButton(self.grpboxGridColors)
        self.radbtnGridBlack.setGeometry(QtCore.QRect(20, 70, 111, 20))
        self.radbtnGridBlack.setChecked(True)
        self.radbtnGridBlack.setObjectName("radbtnGridBlack")
        self.radbtnGridYellow = QtWidgets.QRadioButton(self.grpboxGridColors)
        self.radbtnGridYellow.setGeometry(QtCore.QRect(20, 100, 111, 20))
        self.radbtnGridYellow.setObjectName("radbtnGridYellow")
        self.radbtnGridGreen = QtWidgets.QRadioButton(self.grpboxGridColors)
        self.radbtnGridGreen.setGeometry(QtCore.QRect(20, 130, 95, 20))
        self.radbtnGridGreen.setObjectName("radbtnGridGreen")
        self.grpboxSaveFrames = QtWidgets.QGroupBox(dialogConfig)
        self.grpboxSaveFrames.setGeometry(QtCore.QRect(270, 30, 691, 151))
        self.grpboxSaveFrames.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.grpboxSaveFrames.setFont(font)
        self.grpboxSaveFrames.setStyleSheet("")
        self.grpboxSaveFrames.setCheckable(True)
        self.grpboxSaveFrames.setChecked(True)
        self.grpboxSaveFrames.setObjectName("grpboxSaveFrames")
        self.radbtnNoAskFrames = QtWidgets.QRadioButton(self.grpboxSaveFrames)
        self.radbtnNoAskFrames.setGeometry(QtCore.QRect(40, 60, 311, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.radbtnNoAskFrames.setFont(font)
        self.radbtnNoAskFrames.setChecked(False)
        self.radbtnNoAskFrames.setObjectName("radbtnNoAskFrames")
        self.radbtnAskFrames = QtWidgets.QRadioButton(self.grpboxSaveFrames)
        self.radbtnAskFrames.setGeometry(QtCore.QRect(40, 30, 291, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.radbtnAskFrames.setFont(font)
        self.radbtnAskFrames.setChecked(True)
        self.radbtnAskFrames.setObjectName("radbtnAskFrames")
        self.btnSaveDirectoryFrames = QtWidgets.QPushButton(self.grpboxSaveFrames)
        self.btnSaveDirectoryFrames.setGeometry(QtCore.QRect(610, 100, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btnSaveDirectoryFrames.setFont(font)
        self.btnSaveDirectoryFrames.setObjectName("btnSaveDirectoryFrames")
        self.lblSaveDirectoryFrames = QtWidgets.QLabel(self.grpboxSaveFrames)
        self.lblSaveDirectoryFrames.setGeometry(QtCore.QRect(40, 97, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lblSaveDirectoryFrames.setFont(font)
        self.lblSaveDirectoryFrames.setScaledContents(False)
        self.lblSaveDirectoryFrames.setObjectName("lblSaveDirectoryFrames")
        self.txtSaveDirectoryFrames = QtWidgets.QLineEdit(self.grpboxSaveFrames)
        self.txtSaveDirectoryFrames.setGeometry(QtCore.QRect(130, 100, 471, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.txtSaveDirectoryFrames.setFont(font)
        self.txtSaveDirectoryFrames.setStyleSheet("color: rgb(75, 75, 75);")
        self.txtSaveDirectoryFrames.setObjectName("txtSaveDirectoryFrames")
        self.grpboxFPS = QtWidgets.QGroupBox(dialogConfig)
        self.grpboxFPS.setGeometry(QtCore.QRect(270, 590, 191, 131))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.grpboxFPS.setFont(font)
        self.grpboxFPS.setObjectName("grpboxFPS")
        self.radbtn05fps = QtWidgets.QRadioButton(self.grpboxFPS)
        self.radbtn05fps.setGeometry(QtCore.QRect(30, 40, 95, 20))
        self.radbtn05fps.setObjectName("radbtn05fps")
        self.radbtn10fps = QtWidgets.QRadioButton(self.grpboxFPS)
        self.radbtn10fps.setGeometry(QtCore.QRect(30, 70, 95, 20))
        self.radbtn10fps.setChecked(True)
        self.radbtn10fps.setObjectName("radbtn10fps")
        self.radbtn15fps = QtWidgets.QRadioButton(self.grpboxFPS)
        self.radbtn15fps.setGeometry(QtCore.QRect(30, 100, 95, 20))
        self.radbtn15fps.setChecked(False)
        self.radbtn15fps.setObjectName("radbtn15fps")
        self.grpboxCapLength = QtWidgets.QGroupBox(dialogConfig)
        self.grpboxCapLength.setGeometry(QtCore.QRect(510, 590, 171, 131))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.grpboxCapLength.setFont(font)
        self.grpboxCapLength.setObjectName("grpboxCapLength")
        self.radbtn3Sec = QtWidgets.QRadioButton(self.grpboxCapLength)
        self.radbtn3Sec.setGeometry(QtCore.QRect(30, 40, 95, 20))
        self.radbtn3Sec.setObjectName("radbtn3Sec")
        self.radbtn5Sec = QtWidgets.QRadioButton(self.grpboxCapLength)
        self.radbtn5Sec.setGeometry(QtCore.QRect(30, 70, 95, 20))
        self.radbtn5Sec.setChecked(True)
        self.radbtn5Sec.setObjectName("radbtn5Sec")
        self.radbtn7Sec = QtWidgets.QRadioButton(self.grpboxCapLength)
        self.radbtn7Sec.setGeometry(QtCore.QRect(30, 100, 95, 20))
        self.radbtn7Sec.setObjectName("radbtn7Sec")
        self.grpboxSaveCaps = QtWidgets.QGroupBox(dialogConfig)
        self.grpboxSaveCaps.setGeometry(QtCore.QRect(270, 190, 691, 151))
        self.grpboxSaveCaps.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.grpboxSaveCaps.setFont(font)
        self.grpboxSaveCaps.setStyleSheet("")
        self.grpboxSaveCaps.setCheckable(True)
        self.grpboxSaveCaps.setChecked(True)
        self.grpboxSaveCaps.setObjectName("grpboxSaveCaps")
        self.radbtnNoAskCaps = QtWidgets.QRadioButton(self.grpboxSaveCaps)
        self.radbtnNoAskCaps.setGeometry(QtCore.QRect(40, 60, 311, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.radbtnNoAskCaps.setFont(font)
        self.radbtnNoAskCaps.setChecked(False)
        self.radbtnNoAskCaps.setObjectName("radbtnNoAskCaps")
        self.radbtnAskCaps = QtWidgets.QRadioButton(self.grpboxSaveCaps)
        self.radbtnAskCaps.setGeometry(QtCore.QRect(40, 30, 291, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.radbtnAskCaps.setFont(font)
        self.radbtnAskCaps.setChecked(True)
        self.radbtnAskCaps.setObjectName("radbtnAskCaps")
        self.btnSaveDirectoryCaps = QtWidgets.QPushButton(self.grpboxSaveCaps)
        self.btnSaveDirectoryCaps.setGeometry(QtCore.QRect(610, 100, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btnSaveDirectoryCaps.setFont(font)
        self.btnSaveDirectoryCaps.setObjectName("btnSaveDirectoryCaps")
        self.lblSaveDirectoryCaps = QtWidgets.QLabel(self.grpboxSaveCaps)
        self.lblSaveDirectoryCaps.setGeometry(QtCore.QRect(40, 97, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lblSaveDirectoryCaps.setFont(font)
        self.lblSaveDirectoryCaps.setScaledContents(False)
        self.lblSaveDirectoryCaps.setObjectName("lblSaveDirectoryCaps")
        self.txtSaveDirectoryCaps = QtWidgets.QLineEdit(self.grpboxSaveCaps)
        self.txtSaveDirectoryCaps.setGeometry(QtCore.QRect(132, 100, 471, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.txtSaveDirectoryCaps.setFont(font)
        self.txtSaveDirectoryCaps.setStyleSheet("color: rgb(75, 75, 75);")
        self.txtSaveDirectoryCaps.setObjectName("txtSaveDirectoryCaps")
        self.comboboxVidSource = QtWidgets.QComboBox(dialogConfig)
        self.comboboxVidSource.setEnabled(True)
        self.comboboxVidSource.setGeometry(QtCore.QRect(410, 534, 451, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.comboboxVidSource.setFont(font)
        self.comboboxVidSource.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(75, 75, 75);")
        self.comboboxVidSource.setObjectName("comboboxVidSource")
        self.lblVideoSource = QtWidgets.QLabel(dialogConfig)
        self.lblVideoSource.setGeometry(QtCore.QRect(280, 540, 121, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lblVideoSource.setFont(font)
        self.lblVideoSource.setObjectName("lblVideoSource")
        self.grpboxGridsDirectory = QtWidgets.QGroupBox(dialogConfig)
        self.grpboxGridsDirectory.setGeometry(QtCore.QRect(270, 350, 691, 81))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.grpboxGridsDirectory.setFont(font)
        self.grpboxGridsDirectory.setObjectName("grpboxGridsDirectory")
        self.btnGridsDirectory = QtWidgets.QPushButton(self.grpboxGridsDirectory)
        self.btnGridsDirectory.setGeometry(QtCore.QRect(610, 30, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btnGridsDirectory.setFont(font)
        self.btnGridsDirectory.setObjectName("btnGridsDirectory")
        self.txtGridsDirectory = QtWidgets.QLineEdit(self.grpboxGridsDirectory)
        self.txtGridsDirectory.setGeometry(QtCore.QRect(130, 30, 471, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.txtGridsDirectory.setFont(font)
        self.txtGridsDirectory.setStyleSheet("color: rgb(75, 75, 75);")
        self.txtGridsDirectory.setObjectName("txtGridsDirectory")
        self.lblGridsDirectory = QtWidgets.QLabel(self.grpboxGridsDirectory)
        self.lblGridsDirectory.setGeometry(QtCore.QRect(40, 30, 101, 31))
        self.lblGridsDirectory.setObjectName("lblGridsDirectory")
        self.grpboxPVRDirectory = QtWidgets.QGroupBox(dialogConfig)
        self.grpboxPVRDirectory.setGeometry(QtCore.QRect(270, 440, 691, 80))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.grpboxPVRDirectory.setFont(font)
        self.grpboxPVRDirectory.setCheckable(True)
        self.grpboxPVRDirectory.setChecked(False)
        self.grpboxPVRDirectory.setObjectName("grpboxPVRDirectory")
        self.lblPVRDirectory = QtWidgets.QLabel(self.grpboxPVRDirectory)
        self.lblPVRDirectory.setGeometry(QtCore.QRect(30, 30, 91, 31))
        self.lblPVRDirectory.setObjectName("lblPVRDirectory")
        self.txtPVRDirectory = QtWidgets.QLineEdit(self.grpboxPVRDirectory)
        self.txtPVRDirectory.setGeometry(QtCore.QRect(120, 30, 481, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.txtPVRDirectory.setFont(font)
        self.txtPVRDirectory.setObjectName("txtPVRDirectory")
        self.btnPVRDirectory = QtWidgets.QPushButton(self.grpboxPVRDirectory)
        self.btnPVRDirectory.setGeometry(QtCore.QRect(610, 30, 71, 28))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btnPVRDirectory.setFont(font)
        self.btnPVRDirectory.setObjectName("btnPVRDirectory")
        self.grpboxDiscipline = QtWidgets.QGroupBox(dialogConfig)
        self.grpboxDiscipline.setGeometry(QtCore.QRect(740, 590, 161, 131))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.grpboxDiscipline.setFont(font)
        self.grpboxDiscipline.setObjectName("grpboxDiscipline")
        self.radbtnWaterski = QtWidgets.QRadioButton(self.grpboxDiscipline)
        self.radbtnWaterski.setGeometry(QtCore.QRect(30, 30, 141, 31))
        self.radbtnWaterski.setChecked(True)
        self.radbtnWaterski.setObjectName("radbtnWaterski")
        self.radbtnSitski = QtWidgets.QRadioButton(self.grpboxDiscipline)
        self.radbtnSitski.setGeometry(QtCore.QRect(30, 60, 131, 31))
        self.radbtnSitski.setObjectName("radbtnSitski")
        self.radbtnBarefoot = QtWidgets.QRadioButton(self.grpboxDiscipline)
        self.radbtnBarefoot.setGeometry(QtCore.QRect(30, 90, 121, 31))
        self.radbtnBarefoot.setObjectName("radbtnBarefoot")
        self.grpboxGrids = QtWidgets.QGroupBox(dialogConfig)
        self.grpboxGrids.setGeometry(QtCore.QRect(30, 20, 201, 161))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.grpboxGrids.setFont(font)
        self.grpboxGrids.setObjectName("grpboxGrids")
        self.radbtnGrids1 = QtWidgets.QRadioButton(self.grpboxGrids)
        self.radbtnGrids1.setGeometry(QtCore.QRect(10, 40, 95, 20))
        self.radbtnGrids1.setChecked(True)
        self.radbtnGrids1.setObjectName("radbtnGrids1")
        self.radbtnGrids2 = QtWidgets.QRadioButton(self.grpboxGrids)
        self.radbtnGrids2.setGeometry(QtCore.QRect(10, 70, 95, 20))
        self.radbtnGrids2.setObjectName("radbtnGrids2")
        self.radbtnGrids3 = QtWidgets.QRadioButton(self.grpboxGrids)
        self.radbtnGrids3.setGeometry(QtCore.QRect(10, 100, 95, 20))
        self.radbtnGrids3.setObjectName("radbtnGrids3")
        self.radbtnGrids4 = QtWidgets.QRadioButton(self.grpboxGrids)
        self.radbtnGrids4.setGeometry(QtCore.QRect(10, 130, 95, 20))
        self.radbtnGrids4.setObjectName("radbtnGrids4")
        self.grpboxHomoGridColors = QtWidgets.QGroupBox(dialogConfig)
        self.grpboxHomoGridColors.setGeometry(QtCore.QRect(30, 560, 201, 161))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.grpboxHomoGridColors.setFont(font)
        self.grpboxHomoGridColors.setObjectName("grpboxHomoGridColors")
        self.radbtnHomoGridRed = QtWidgets.QRadioButton(self.grpboxHomoGridColors)
        self.radbtnHomoGridRed.setGeometry(QtCore.QRect(10, 40, 95, 20))
        self.radbtnHomoGridRed.setChecked(True)
        self.radbtnHomoGridRed.setObjectName("radbtnHomoGridRed")
        self.radbtnHomoGridBlack = QtWidgets.QRadioButton(self.grpboxHomoGridColors)
        self.radbtnHomoGridBlack.setGeometry(QtCore.QRect(10, 70, 95, 20))
        self.radbtnHomoGridBlack.setObjectName("radbtnHomoGridBlack")
        self.radbtnHomoGridYellow = QtWidgets.QRadioButton(self.grpboxHomoGridColors)
        self.radbtnHomoGridYellow.setGeometry(QtCore.QRect(10, 100, 95, 20))
        self.radbtnHomoGridYellow.setObjectName("radbtnHomoGridYellow")
        self.radbtnHomoGridGreen = QtWidgets.QRadioButton(self.grpboxHomoGridColors)
        self.radbtnHomoGridGreen.setGeometry(QtCore.QRect(10, 130, 95, 20))
        self.radbtnHomoGridGreen.setObjectName("radbtnHomoGridGreen")

        self.retranslateUi(dialogConfig)
        self.buttonBox.accepted.connect(dialogConfig.accept)
        self.buttonBox.rejected.connect(dialogConfig.reject)
        QtCore.QMetaObject.connectSlotsByName(dialogConfig)

    def retranslateUi(self, dialogConfig):
        _translate = QtCore.QCoreApplication.translate
        dialogConfig.setWindowTitle(_translate("dialogConfig", "Video Tape Measure Configurations"))
        self.grpboxJumpColors.setTitle(_translate("dialogConfig", "Jump Marker Color"))
        self.radbtnJumpRed.setText(_translate("dialogConfig", "Red"))
        self.radbtnJumpBlack.setText(_translate("dialogConfig", "Black"))
        self.radbtnJumpYellow.setText(_translate("dialogConfig", "Yellow"))
        self.radbtnJumpGreen.setText(_translate("dialogConfig", "Green"))
        self.grpboxGridColors.setTitle(_translate("dialogConfig", "Grid Marker Color"))
        self.radbtnGridRed.setText(_translate("dialogConfig", "Red"))
        self.radbtnGridBlack.setText(_translate("dialogConfig", "Black"))
        self.radbtnGridYellow.setText(_translate("dialogConfig", "Yellow"))
        self.radbtnGridGreen.setText(_translate("dialogConfig", "Green"))
        self.grpboxSaveFrames.setTitle(_translate("dialogConfig", "Save Jump Pictures"))
        self.radbtnNoAskFrames.setText(_translate("dialogConfig", "Save Without Asking"))
        self.radbtnAskFrames.setText(_translate("dialogConfig", "Ask Before Saving"))
        self.btnSaveDirectoryFrames.setText(_translate("dialogConfig", "Find"))
        self.lblSaveDirectoryFrames.setText(_translate("dialogConfig", "Directory"))
        self.grpboxFPS.setTitle(_translate("dialogConfig", "Frames per Second"))
        self.radbtn05fps.setText(_translate("dialogConfig", "  5 fps"))
        self.radbtn10fps.setText(_translate("dialogConfig", "10 fps"))
        self.radbtn15fps.setText(_translate("dialogConfig", "15 fps"))
        self.grpboxCapLength.setTitle(_translate("dialogConfig", "Capture Duration"))
        self.radbtn3Sec.setText(_translate("dialogConfig", "3 sec"))
        self.radbtn5Sec.setText(_translate("dialogConfig", "5 sec"))
        self.radbtn7Sec.setText(_translate("dialogConfig", "7 sec"))
        self.grpboxSaveCaps.setTitle(_translate("dialogConfig", "Save Captured Videos"))
        self.radbtnNoAskCaps.setText(_translate("dialogConfig", "Save Without Asking"))
        self.radbtnAskCaps.setText(_translate("dialogConfig", "Ask Before Saving"))
        self.btnSaveDirectoryCaps.setText(_translate("dialogConfig", "Find"))
        self.lblSaveDirectoryCaps.setText(_translate("dialogConfig", "Directory"))
        self.lblVideoSource.setText(_translate("dialogConfig", "Video Source"))
        self.grpboxGridsDirectory.setTitle(_translate("dialogConfig", "Grid Setups"))
        self.btnGridsDirectory.setText(_translate("dialogConfig", "Find"))
        self.lblGridsDirectory.setText(_translate("dialogConfig", "Directory"))
        self.grpboxPVRDirectory.setTitle(_translate("dialogConfig", "Record to PVR"))
        self.lblPVRDirectory.setText(_translate("dialogConfig", "Directory"))
        self.btnPVRDirectory.setText(_translate("dialogConfig", "Find"))
        self.grpboxDiscipline.setTitle(_translate("dialogConfig", "Discipline"))
        self.radbtnWaterski.setText(_translate("dialogConfig", "Water Ski"))
        self.radbtnSitski.setText(_translate("dialogConfig", "Sit Ski"))
        self.radbtnBarefoot.setText(_translate("dialogConfig", "Barefoot"))
        self.grpboxGrids.setTitle(_translate("dialogConfig", "Number of Grids"))
        self.radbtnGrids1.setText(_translate("dialogConfig", "1"))
        self.radbtnGrids2.setText(_translate("dialogConfig", "2"))
        self.radbtnGrids3.setText(_translate("dialogConfig", "3"))
        self.radbtnGrids4.setText(_translate("dialogConfig", "4"))
        self.grpboxHomoGridColors.setTitle(_translate("dialogConfig", "Homologation Grid"))
        self.radbtnHomoGridRed.setText(_translate("dialogConfig", "Red"))
        self.radbtnHomoGridBlack.setText(_translate("dialogConfig", "Black"))
        self.radbtnHomoGridYellow.setText(_translate("dialogConfig", "Yellow"))
        self.radbtnHomoGridGreen.setText(_translate("dialogConfig", "Green"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    dialogConfig = QtWidgets.QDialog()
    ui = Ui_dialogConfig()
    ui.setupUi(dialogConfig)
    dialogConfig.show()
    sys.exit(app.exec_())

