# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Slalo\Dropbox\PythonScripts\VTM\VTMLayout21.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1999, 1001)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        MainWindow.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../.designer/backup/VTMIconSmall.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lblSurveyULY = QtWidgets.QLabel(self.centralwidget)
        self.lblSurveyULY.setGeometry(QtCore.QRect(1610, 350, 21, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lblSurveyULY.setFont(font)
        self.lblSurveyULY.setAlignment(QtCore.Qt.AlignCenter)
        self.lblSurveyULY.setObjectName("lblSurveyULY")
        self.lblSurveyULX = QtWidgets.QLabel(self.centralwidget)
        self.lblSurveyULX.setGeometry(QtCore.QRect(1520, 350, 21, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lblSurveyULX.setFont(font)
        self.lblSurveyULX.setAlignment(QtCore.Qt.AlignCenter)
        self.lblSurveyULX.setObjectName("lblSurveyULX")
        self.txtSurveyULY = QtWidgets.QLineEdit(self.centralwidget)
        self.txtSurveyULY.setGeometry(QtCore.QRect(1630, 340, 61, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtSurveyULY.sizePolicy().hasHeightForWidth())
        self.txtSurveyULY.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.txtSurveyULY.setFont(font)
        self.txtSurveyULY.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.txtSurveyULY.setAlignment(QtCore.Qt.AlignCenter)
        self.txtSurveyULY.setReadOnly(False)
        self.txtSurveyULY.setObjectName("txtSurveyULY")
        self.txtSurveyULX = QtWidgets.QLineEdit(self.centralwidget)
        self.txtSurveyULX.setGeometry(QtCore.QRect(1540, 340, 61, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtSurveyULX.sizePolicy().hasHeightForWidth())
        self.txtSurveyULX.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.txtSurveyULX.setFont(font)
        self.txtSurveyULX.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.txtSurveyULX.setAutoFillBackground(True)
        self.txtSurveyULX.setInputMethodHints(QtCore.Qt.ImhNone)
        self.txtSurveyULX.setAlignment(QtCore.Qt.AlignCenter)
        self.txtSurveyULX.setReadOnly(False)
        self.txtSurveyULX.setObjectName("txtSurveyULX")
        self.lblSurveyURY = QtWidgets.QLabel(self.centralwidget)
        self.lblSurveyURY.setGeometry(QtCore.QRect(1810, 350, 21, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lblSurveyURY.setFont(font)
        self.lblSurveyURY.setAlignment(QtCore.Qt.AlignCenter)
        self.lblSurveyURY.setObjectName("lblSurveyURY")
        self.txtSurveyURY = QtWidgets.QLineEdit(self.centralwidget)
        self.txtSurveyURY.setGeometry(QtCore.QRect(1830, 340, 61, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtSurveyURY.sizePolicy().hasHeightForWidth())
        self.txtSurveyURY.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.txtSurveyURY.setFont(font)
        self.txtSurveyURY.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.txtSurveyURY.setAlignment(QtCore.Qt.AlignCenter)
        self.txtSurveyURY.setReadOnly(False)
        self.txtSurveyURY.setObjectName("txtSurveyURY")
        self.txtSurveyURX = QtWidgets.QLineEdit(self.centralwidget)
        self.txtSurveyURX.setGeometry(QtCore.QRect(1740, 340, 61, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtSurveyURX.sizePolicy().hasHeightForWidth())
        self.txtSurveyURX.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.txtSurveyURX.setFont(font)
        self.txtSurveyURX.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.txtSurveyURX.setAlignment(QtCore.Qt.AlignCenter)
        self.txtSurveyURX.setReadOnly(False)
        self.txtSurveyURX.setObjectName("txtSurveyURX")
        self.lblSurveyURX = QtWidgets.QLabel(self.centralwidget)
        self.lblSurveyURX.setGeometry(QtCore.QRect(1720, 350, 21, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lblSurveyURX.setFont(font)
        self.lblSurveyURX.setAlignment(QtCore.Qt.AlignCenter)
        self.lblSurveyURX.setObjectName("lblSurveyURX")
        self.lblSurveyLLY = QtWidgets.QLabel(self.centralwidget)
        self.lblSurveyLLY.setGeometry(QtCore.QRect(1610, 410, 21, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lblSurveyLLY.setFont(font)
        self.lblSurveyLLY.setAlignment(QtCore.Qt.AlignCenter)
        self.lblSurveyLLY.setObjectName("lblSurveyLLY")
        self.txtSurveyLLY = QtWidgets.QLineEdit(self.centralwidget)
        self.txtSurveyLLY.setGeometry(QtCore.QRect(1630, 400, 61, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtSurveyLLY.sizePolicy().hasHeightForWidth())
        self.txtSurveyLLY.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.txtSurveyLLY.setFont(font)
        self.txtSurveyLLY.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.txtSurveyLLY.setAlignment(QtCore.Qt.AlignCenter)
        self.txtSurveyLLY.setReadOnly(False)
        self.txtSurveyLLY.setObjectName("txtSurveyLLY")
        self.txtSurveyLLX = QtWidgets.QLineEdit(self.centralwidget)
        self.txtSurveyLLX.setGeometry(QtCore.QRect(1540, 400, 61, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtSurveyLLX.sizePolicy().hasHeightForWidth())
        self.txtSurveyLLX.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.txtSurveyLLX.setFont(font)
        self.txtSurveyLLX.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.txtSurveyLLX.setAlignment(QtCore.Qt.AlignCenter)
        self.txtSurveyLLX.setReadOnly(False)
        self.txtSurveyLLX.setObjectName("txtSurveyLLX")
        self.lblSurveyLLX = QtWidgets.QLabel(self.centralwidget)
        self.lblSurveyLLX.setGeometry(QtCore.QRect(1520, 410, 21, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lblSurveyLLX.setFont(font)
        self.lblSurveyLLX.setAlignment(QtCore.Qt.AlignCenter)
        self.lblSurveyLLX.setObjectName("lblSurveyLLX")
        self.txtSurveyLRX = QtWidgets.QLineEdit(self.centralwidget)
        self.txtSurveyLRX.setGeometry(QtCore.QRect(1740, 400, 61, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtSurveyLRX.sizePolicy().hasHeightForWidth())
        self.txtSurveyLRX.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.txtSurveyLRX.setFont(font)
        self.txtSurveyLRX.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.txtSurveyLRX.setAlignment(QtCore.Qt.AlignCenter)
        self.txtSurveyLRX.setReadOnly(False)
        self.txtSurveyLRX.setObjectName("txtSurveyLRX")
        self.lblSurveyLRY = QtWidgets.QLabel(self.centralwidget)
        self.lblSurveyLRY.setGeometry(QtCore.QRect(1810, 410, 21, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lblSurveyLRY.setFont(font)
        self.lblSurveyLRY.setAlignment(QtCore.Qt.AlignCenter)
        self.lblSurveyLRY.setObjectName("lblSurveyLRY")
        self.txtSurveyLRY = QtWidgets.QLineEdit(self.centralwidget)
        self.txtSurveyLRY.setGeometry(QtCore.QRect(1830, 400, 61, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtSurveyLRY.sizePolicy().hasHeightForWidth())
        self.txtSurveyLRY.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.txtSurveyLRY.setFont(font)
        self.txtSurveyLRY.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.txtSurveyLRY.setAlignment(QtCore.Qt.AlignCenter)
        self.txtSurveyLRY.setReadOnly(False)
        self.txtSurveyLRY.setObjectName("txtSurveyLRY")
        self.lblSurveyLRX = QtWidgets.QLabel(self.centralwidget)
        self.lblSurveyLRX.setGeometry(QtCore.QRect(1720, 410, 21, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lblSurveyLRX.setFont(font)
        self.lblSurveyLRX.setAlignment(QtCore.Qt.AlignCenter)
        self.lblSurveyLRX.setObjectName("lblSurveyLRX")
        self.lblSurveyJpX = QtWidgets.QLabel(self.centralwidget)
        self.lblSurveyJpX.setGeometry(QtCore.QRect(1720, 520, 21, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lblSurveyJpX.setFont(font)
        self.lblSurveyJpX.setAlignment(QtCore.Qt.AlignCenter)
        self.lblSurveyJpX.setObjectName("lblSurveyJpX")
        self.txtSurveyRpY = QtWidgets.QLineEdit(self.centralwidget)
        self.txtSurveyRpY.setGeometry(QtCore.QRect(1830, 510, 61, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtSurveyRpY.sizePolicy().hasHeightForWidth())
        self.txtSurveyRpY.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.txtSurveyRpY.setFont(font)
        self.txtSurveyRpY.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.txtSurveyRpY.setAlignment(QtCore.Qt.AlignCenter)
        self.txtSurveyRpY.setReadOnly(False)
        self.txtSurveyRpY.setObjectName("txtSurveyRpY")
        self.lblRamp = QtWidgets.QLabel(self.centralwidget)
        self.lblRamp.setGeometry(QtCore.QRect(1750, 550, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.lblRamp.setFont(font)
        self.lblRamp.setAlignment(QtCore.Qt.AlignCenter)
        self.lblRamp.setObjectName("lblRamp")
        self.txtSurveyRpX = QtWidgets.QLineEdit(self.centralwidget)
        self.txtSurveyRpX.setGeometry(QtCore.QRect(1740, 510, 61, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtSurveyRpX.sizePolicy().hasHeightForWidth())
        self.txtSurveyRpX.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.txtSurveyRpX.setFont(font)
        self.txtSurveyRpX.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.txtSurveyRpX.setAlignment(QtCore.Qt.AlignCenter)
        self.txtSurveyRpX.setReadOnly(False)
        self.txtSurveyRpX.setObjectName("txtSurveyRpX")
        self.lblSurveyJpY = QtWidgets.QLabel(self.centralwidget)
        self.lblSurveyJpY.setGeometry(QtCore.QRect(1810, 520, 21, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lblSurveyJpY.setFont(font)
        self.lblSurveyJpY.setAlignment(QtCore.Qt.AlignCenter)
        self.lblSurveyJpY.setObjectName("lblSurveyJpY")
        self.lblSurveyCkX = QtWidgets.QLabel(self.centralwidget)
        self.lblSurveyCkX.setGeometry(QtCore.QRect(1520, 520, 21, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lblSurveyCkX.setFont(font)
        self.lblSurveyCkX.setAlignment(QtCore.Qt.AlignCenter)
        self.lblSurveyCkX.setObjectName("lblSurveyCkX")
        self.lblSurveyCkY = QtWidgets.QLabel(self.centralwidget)
        self.lblSurveyCkY.setGeometry(QtCore.QRect(1610, 520, 21, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lblSurveyCkY.setFont(font)
        self.lblSurveyCkY.setAlignment(QtCore.Qt.AlignCenter)
        self.lblSurveyCkY.setObjectName("lblSurveyCkY")
        self.txtSurveyCkY = QtWidgets.QLineEdit(self.centralwidget)
        self.txtSurveyCkY.setGeometry(QtCore.QRect(1630, 510, 61, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtSurveyCkY.sizePolicy().hasHeightForWidth())
        self.txtSurveyCkY.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.txtSurveyCkY.setFont(font)
        self.txtSurveyCkY.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.txtSurveyCkY.setAlignment(QtCore.Qt.AlignCenter)
        self.txtSurveyCkY.setReadOnly(False)
        self.txtSurveyCkY.setObjectName("txtSurveyCkY")
        self.txtSurveyCkX = QtWidgets.QLineEdit(self.centralwidget)
        self.txtSurveyCkX.setGeometry(QtCore.QRect(1540, 510, 61, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtSurveyCkX.sizePolicy().hasHeightForWidth())
        self.txtSurveyCkX.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.txtSurveyCkX.setFont(font)
        self.txtSurveyCkX.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.txtSurveyCkX.setAlignment(QtCore.Qt.AlignCenter)
        self.txtSurveyCkX.setReadOnly(False)
        self.txtSurveyCkX.setObjectName("txtSurveyCkX")
        self.btnHitRamp = QtWidgets.QPushButton(self.centralwidget)
        self.btnHitRamp.setGeometry(QtCore.QRect(1370, 10, 171, 91))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btnHitRamp.setFont(font)
        self.btnHitRamp.setAutoDefault(True)
        self.btnHitRamp.setDefault(True)
        self.btnHitRamp.setObjectName("btnHitRamp")
        self.cboxSkierNames = CustomCombo(self.centralwidget)
        self.cboxSkierNames.setGeometry(QtCore.QRect(270, 830, 471, 41))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.HighlightedText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.HighlightedText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 120, 215))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.HighlightedText, brush)
        self.cboxSkierNames.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cboxSkierNames.setFont(font)
        self.cboxSkierNames.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.cboxSkierNames.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.cboxSkierNames.setEditable(True)
        self.cboxSkierNames.setObjectName("cboxSkierNames")
        self.lblSkierName = QtWidgets.QLabel(self.centralwidget)
        self.lblSkierName.setGeometry(QtCore.QRect(160, 840, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lblSkierName.setFont(font)
        self.lblSkierName.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblSkierName.setObjectName("lblSkierName")
        self.lblJump = QtWidgets.QLabel(self.centralwidget)
        self.lblJump.setGeometry(QtCore.QRect(750, 840, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lblJump.setFont(font)
        self.lblJump.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblJump.setObjectName("lblJump")
        self.lblRound = QtWidgets.QLabel(self.centralwidget)
        self.lblRound.setGeometry(QtCore.QRect(870, 840, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lblRound.setFont(font)
        self.lblRound.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblRound.setObjectName("lblRound")
        self.btnNextJump = QtWidgets.QPushButton(self.centralwidget)
        self.btnNextJump.setGeometry(QtCore.QRect(1390, 170, 151, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btnNextJump.setFont(font)
        self.btnNextJump.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btnNextJump.setObjectName("btnNextJump")
        self.chkboxShowBuoys = QtWidgets.QCheckBox(self.centralwidget)
        self.chkboxShowBuoys.setGeometry(QtCore.QRect(1020, 811, 211, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.chkboxShowBuoys.setFont(font)
        self.chkboxShowBuoys.setFocusPolicy(QtCore.Qt.NoFocus)
        self.chkboxShowBuoys.setObjectName("chkboxShowBuoys")
        self.chkboxShowHomoLevel = QtWidgets.QCheckBox(self.centralwidget)
        self.chkboxShowHomoLevel.setGeometry(QtCore.QRect(1020, 841, 261, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.chkboxShowHomoLevel.setFont(font)
        self.chkboxShowHomoLevel.setFocusPolicy(QtCore.Qt.NoFocus)
        self.chkboxShowHomoLevel.setAutoExclusive(True)
        self.chkboxShowHomoLevel.setObjectName("chkboxShowHomoLevel")
        self.radbtnUL = QtWidgets.QRadioButton(self.centralwidget)
        self.radbtnUL.setGeometry(QtCore.QRect(1540, 300, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.radbtnUL.setFont(font)
        self.radbtnUL.setFocusPolicy(QtCore.Qt.NoFocus)
        self.radbtnUL.setChecked(True)
        self.radbtnUL.setObjectName("radbtnUL")
        self.radbtnUR = QtWidgets.QRadioButton(self.centralwidget)
        self.radbtnUR.setGeometry(QtCore.QRect(1740, 300, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.radbtnUR.setFont(font)
        self.radbtnUR.setFocusPolicy(QtCore.Qt.NoFocus)
        self.radbtnUR.setObjectName("radbtnUR")
        self.radbtnLL = QtWidgets.QRadioButton(self.centralwidget)
        self.radbtnLL.setGeometry(QtCore.QRect(1530, 440, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.radbtnLL.setFont(font)
        self.radbtnLL.setFocusPolicy(QtCore.Qt.NoFocus)
        self.radbtnLL.setObjectName("radbtnLL")
        self.radbtnLR = QtWidgets.QRadioButton(self.centralwidget)
        self.radbtnLR.setGeometry(QtCore.QRect(1740, 440, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.radbtnLR.setFont(font)
        self.radbtnLR.setFocusPolicy(QtCore.Qt.NoFocus)
        self.radbtnLR.setObjectName("radbtnLR")
        self.radbtnCheck = QtWidgets.QRadioButton(self.centralwidget)
        self.radbtnCheck.setGeometry(QtCore.QRect(1530, 550, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.radbtnCheck.setFont(font)
        self.radbtnCheck.setFocusPolicy(QtCore.Qt.NoFocus)
        self.radbtnCheck.setObjectName("radbtnCheck")
        self.frameSetup = QtWidgets.QFrame(self.centralwidget)
        self.frameSetup.setGeometry(QtCore.QRect(1510, 290, 401, 391))
        self.frameSetup.setAutoFillBackground(False)
        self.frameSetup.setFrameShape(QtWidgets.QFrame.Box)
        self.frameSetup.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frameSetup.setLineWidth(1)
        self.frameSetup.setObjectName("frameSetup")
        self.line = QtWidgets.QFrame(self.frameSetup)
        self.line.setGeometry(QtCore.QRect(0, 198, 401, 1))
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setLineWidth(1)
        self.line.setMidLineWidth(0)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setObjectName("line")
        self.chkboxLockGridBuoys = QtWidgets.QCheckBox(self.centralwidget)
        self.chkboxLockGridBuoys.setGeometry(QtCore.QRect(1530, 638, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.chkboxLockGridBuoys.setFont(font)
        self.chkboxLockGridBuoys.setFocusPolicy(QtCore.Qt.NoFocus)
        self.chkboxLockGridBuoys.setObjectName("chkboxLockGridBuoys")
        self.btnCheck = QtWidgets.QPushButton(self.centralwidget)
        self.btnCheck.setGeometry(QtCore.QRect(1780, 602, 111, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btnCheck.setFont(font)
        self.btnCheck.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btnCheck.setObjectName("btnCheck")
        self.label_30 = QtWidgets.QLabel(self.centralwidget)
        self.label_30.setGeometry(QtCore.QRect(1645, 788, 21, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_30.setFont(font)
        self.label_30.setAlignment(QtCore.Qt.AlignCenter)
        self.label_30.setObjectName("label_30")
        self.txtImg2GrdX = QtWidgets.QLineEdit(self.centralwidget)
        self.txtImg2GrdX.setEnabled(False)
        self.txtImg2GrdX.setGeometry(QtCore.QRect(1664, 738, 61, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtImg2GrdX.sizePolicy().hasHeightForWidth())
        self.txtImg2GrdX.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.txtImg2GrdX.setFont(font)
        self.txtImg2GrdX.setFocusPolicy(QtCore.Qt.NoFocus)
        self.txtImg2GrdX.setAlignment(QtCore.Qt.AlignCenter)
        self.txtImg2GrdX.setReadOnly(False)
        self.txtImg2GrdX.setObjectName("txtImg2GrdX")
        self.txtImg2GrdY = QtWidgets.QLineEdit(self.centralwidget)
        self.txtImg2GrdY.setEnabled(False)
        self.txtImg2GrdY.setGeometry(QtCore.QRect(1664, 778, 61, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtImg2GrdY.sizePolicy().hasHeightForWidth())
        self.txtImg2GrdY.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.txtImg2GrdY.setFont(font)
        self.txtImg2GrdY.setFocusPolicy(QtCore.Qt.NoFocus)
        self.txtImg2GrdY.setAlignment(QtCore.Qt.AlignCenter)
        self.txtImg2GrdY.setReadOnly(False)
        self.txtImg2GrdY.setObjectName("txtImg2GrdY")
        self.label_28 = QtWidgets.QLabel(self.centralwidget)
        self.label_28.setGeometry(QtCore.QRect(1645, 748, 21, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_28.setFont(font)
        self.label_28.setAlignment(QtCore.Qt.AlignCenter)
        self.label_28.setObjectName("label_28")
        self.frameVerify = QtWidgets.QFrame(self.centralwidget)
        self.frameVerify.setEnabled(True)
        self.frameVerify.setGeometry(QtCore.QRect(1640, 700, 271, 131))
        self.frameVerify.setAutoFillBackground(False)
        self.frameVerify.setFrameShape(QtWidgets.QFrame.Box)
        self.frameVerify.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameVerify.setObjectName("frameVerify")
        self.chkboxVerify = QtWidgets.QCheckBox(self.centralwidget)
        self.chkboxVerify.setEnabled(False)
        self.chkboxVerify.setGeometry(QtCore.QRect(1740, 700, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.chkboxVerify.setFont(font)
        self.chkboxVerify.setFocusPolicy(QtCore.Qt.NoFocus)
        self.chkboxVerify.setObjectName("chkboxVerify")
        self.verifyLabel = QtWidgets.QLabel(self.centralwidget)
        self.verifyLabel.setGeometry(QtCore.QRect(1870, 690, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.verifyLabel.setFont(font)
        self.verifyLabel.setAutoFillBackground(False)
        self.verifyLabel.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.verifyLabel.setFrameShape(QtWidgets.QFrame.Box)
        self.verifyLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.verifyLabel.setWordWrap(True)
        self.verifyLabel.setObjectName("verifyLabel")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(1756, 812, 55, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(1669, 812, 55, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.txtVerifyScreenX = QtWidgets.QLineEdit(self.centralwidget)
        self.txtVerifyScreenX.setEnabled(False)
        self.txtVerifyScreenX.setGeometry(QtCore.QRect(1753, 738, 61, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtVerifyScreenX.sizePolicy().hasHeightForWidth())
        self.txtVerifyScreenX.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.txtVerifyScreenX.setFont(font)
        self.txtVerifyScreenX.setFocusPolicy(QtCore.Qt.NoFocus)
        self.txtVerifyScreenX.setAlignment(QtCore.Qt.AlignCenter)
        self.txtVerifyScreenX.setReadOnly(False)
        self.txtVerifyScreenX.setObjectName("txtVerifyScreenX")
        self.label_31 = QtWidgets.QLabel(self.centralwidget)
        self.label_31.setGeometry(QtCore.QRect(1734, 788, 21, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_31.setFont(font)
        self.label_31.setAlignment(QtCore.Qt.AlignCenter)
        self.label_31.setObjectName("label_31")
        self.label_32 = QtWidgets.QLabel(self.centralwidget)
        self.label_32.setGeometry(QtCore.QRect(1734, 748, 21, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_32.setFont(font)
        self.label_32.setAlignment(QtCore.Qt.AlignCenter)
        self.label_32.setObjectName("label_32")
        self.txtVerifyScreenY = QtWidgets.QLineEdit(self.centralwidget)
        self.txtVerifyScreenY.setEnabled(False)
        self.txtVerifyScreenY.setGeometry(QtCore.QRect(1753, 778, 61, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtVerifyScreenY.sizePolicy().hasHeightForWidth())
        self.txtVerifyScreenY.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.txtVerifyScreenY.setFont(font)
        self.txtVerifyScreenY.setFocusPolicy(QtCore.Qt.NoFocus)
        self.txtVerifyScreenY.setAlignment(QtCore.Qt.AlignCenter)
        self.txtVerifyScreenY.setReadOnly(False)
        self.txtVerifyScreenY.setObjectName("txtVerifyScreenY")
        self.vidWindow = QtWidgets.QLabel(self.centralwidget)
        self.vidWindow.setGeometry(QtCore.QRect(20, 10, 1337, 752))
        self.vidWindow.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.vidWindow.setText("")
        self.vidWindow.setObjectName("vidWindow")
        self.chkboxSetup = QtWidgets.QCheckBox(self.centralwidget)
        self.chkboxSetup.setGeometry(QtCore.QRect(1530, 600, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.chkboxSetup.setFont(font)
        self.chkboxSetup.setFocusPolicy(QtCore.Qt.NoFocus)
        self.chkboxSetup.setChecked(True)
        self.chkboxSetup.setObjectName("chkboxSetup")
        self.lblLoupe = QtWidgets.QLabel(self.centralwidget)
        self.lblLoupe.setGeometry(QtCore.QRect(1390, 700, 240, 240))
        self.lblLoupe.setFrameShape(QtWidgets.QFrame.Box)
        self.lblLoupe.setText("")
        self.lblLoupe.setObjectName("lblLoupe")
        self.grpboxLoupe = QtWidgets.QGroupBox(self.centralwidget)
        self.grpboxLoupe.setGeometry(QtCore.QRect(1300, 780, 81, 161))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.grpboxLoupe.setFont(font)
        self.grpboxLoupe.setObjectName("grpboxLoupe")
        self.radbtn4x = QtWidgets.QRadioButton(self.grpboxLoupe)
        self.radbtn4x.setGeometry(QtCore.QRect(20, 100, 61, 20))
        self.radbtn4x.setFocusPolicy(QtCore.Qt.NoFocus)
        self.radbtn4x.setChecked(True)
        self.radbtn4x.setObjectName("radbtn4x")
        self.radbtn3x = QtWidgets.QRadioButton(self.grpboxLoupe)
        self.radbtn3x.setGeometry(QtCore.QRect(20, 70, 61, 20))
        self.radbtn3x.setFocusPolicy(QtCore.Qt.NoFocus)
        self.radbtn3x.setChecked(False)
        self.radbtn3x.setObjectName("radbtn3x")
        self.radbtn5x = QtWidgets.QRadioButton(self.grpboxLoupe)
        self.radbtn5x.setGeometry(QtCore.QRect(20, 130, 61, 20))
        self.radbtn5x.setFocusPolicy(QtCore.Qt.NoFocus)
        self.radbtn5x.setObjectName("radbtn5x")
        self.radbtn2x = QtWidgets.QRadioButton(self.grpboxLoupe)
        self.radbtn2x.setGeometry(QtCore.QRect(20, 40, 81, 20))
        self.radbtn2x.setFocusPolicy(QtCore.Qt.NoFocus)
        self.radbtn2x.setObjectName("radbtn2x")
        self.vidSlider = QtWidgets.QSlider(self.centralwidget)
        self.vidSlider.setGeometry(QtCore.QRect(20, 790, 1261, 22))
        self.vidSlider.setFocusPolicy(QtCore.Qt.NoFocus)
        self.vidSlider.setMinimum(0)
        self.vidSlider.setOrientation(QtCore.Qt.Horizontal)
        self.vidSlider.setObjectName("vidSlider")
        self.vidReplay = QtWidgets.QLabel(self.centralwidget)
        self.vidReplay.setGeometry(QtCore.QRect(20, 10, 1337, 752))
        self.vidReplay.setAutoFillBackground(True)
        self.vidReplay.setStyleSheet("border-color: rgb(0, 0, 255);")
        self.vidReplay.setInputMethodHints(QtCore.Qt.ImhHiddenText)
        self.vidReplay.setFrameShape(QtWidgets.QFrame.Panel)
        self.vidReplay.setFrameShadow(QtWidgets.QFrame.Plain)
        self.vidReplay.setLineWidth(4)
        self.vidReplay.setText("")
        self.vidReplay.setObjectName("vidReplay")
        self.btnClickDown = QtWidgets.QPushButton(self.centralwidget)
        self.btnClickDown.setGeometry(QtCore.QRect(1420, 398, 41, 41))
        font = QtGui.QFont()
        font.setFamily("Wingdings 3")
        font.setPointSize(20)
        self.btnClickDown.setFont(font)
        self.btnClickDown.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btnClickDown.setObjectName("btnClickDown")
        self.btnClickRight = QtWidgets.QPushButton(self.centralwidget)
        self.btnClickRight.setGeometry(QtCore.QRect(1459, 359, 41, 41))
        font = QtGui.QFont()
        font.setFamily("Wingdings 3")
        font.setPointSize(20)
        self.btnClickRight.setFont(font)
        self.btnClickRight.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btnClickRight.setObjectName("btnClickRight")
        self.btnClickLeft = QtWidgets.QPushButton(self.centralwidget)
        self.btnClickLeft.setGeometry(QtCore.QRect(1381, 359, 41, 41))
        font = QtGui.QFont()
        font.setFamily("Wingdings 3")
        font.setPointSize(20)
        self.btnClickLeft.setFont(font)
        self.btnClickLeft.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btnClickLeft.setObjectName("btnClickLeft")
        self.btnClickUp = QtWidgets.QPushButton(self.centralwidget)
        self.btnClickUp.setGeometry(QtCore.QRect(1420, 320, 41, 41))
        font = QtGui.QFont()
        font.setFamily("Wingdings 3")
        font.setPointSize(20)
        self.btnClickUp.setFont(font)
        self.btnClickUp.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btnClickUp.setObjectName("btnClickUp")
        self.btnReselectFrame = QtWidgets.QPushButton(self.centralwidget)
        self.btnReselectFrame.setGeometry(QtCore.QRect(1390, 230, 151, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btnReselectFrame.setFont(font)
        self.btnReselectFrame.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btnReselectFrame.setObjectName("btnReselectFrame")
        self.lblMeters = QtWidgets.QLabel(self.centralwidget)
        self.lblMeters.setGeometry(QtCore.QRect(1640, 120, 55, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lblMeters.setFont(font)
        self.lblMeters.setObjectName("lblMeters")
        self.lblFeet = QtWidgets.QLabel(self.centralwidget)
        self.lblFeet.setGeometry(QtCore.QRect(1650, 260, 55, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lblFeet.setFont(font)
        self.lblFeet.setObjectName("lblFeet")
        self.spinBoxPass = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBoxPass.setGeometry(QtCore.QRect(810, 830, 51, 41))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.HighlightedText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.HighlightedText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 120, 215))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.HighlightedText, brush)
        self.spinBoxPass.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.spinBoxPass.setFont(font)
        self.spinBoxPass.setFocusPolicy(QtCore.Qt.NoFocus)
        self.spinBoxPass.setStyleSheet("")
        self.spinBoxPass.setAlignment(QtCore.Qt.AlignCenter)
        self.spinBoxPass.setMinimum(1)
        self.spinBoxPass.setProperty("value", 1)
        self.spinBoxPass.setObjectName("spinBoxPass")
        self.spinBoxRound = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBoxRound.setGeometry(QtCore.QRect(940, 830, 51, 41))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.HighlightedText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.HighlightedText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 120, 215))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.HighlightedText, brush)
        self.spinBoxRound.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.spinBoxRound.setFont(font)
        self.spinBoxRound.setFocusPolicy(QtCore.Qt.NoFocus)
        self.spinBoxRound.setStyleSheet("")
        self.spinBoxRound.setAlignment(QtCore.Qt.AlignCenter)
        self.spinBoxRound.setReadOnly(False)
        self.spinBoxRound.setMinimum(1)
        self.spinBoxRound.setProperty("value", 1)
        self.spinBoxRound.setObjectName("spinBoxRound")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(270, 873, 471, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setItalic(True)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.lblSlider = QtWidgets.QLabel(self.centralwidget)
        self.lblSlider.setGeometry(QtCore.QRect(1250, 800, 41, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lblSlider.setFont(font)
        self.lblSlider.setText("")
        self.lblSlider.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblSlider.setObjectName("lblSlider")
        self.chkboxShowGridAccuracy = QtWidgets.QCheckBox(self.centralwidget)
        self.chkboxShowGridAccuracy.setGeometry(QtCore.QRect(1020, 870, 261, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.chkboxShowGridAccuracy.setFont(font)
        self.chkboxShowGridAccuracy.setFocusPolicy(QtCore.Qt.NoFocus)
        self.chkboxShowGridAccuracy.setAutoExclusive(True)
        self.chkboxShowGridAccuracy.setObjectName("chkboxShowGridAccuracy")
        self.btnCapFrame = QtWidgets.QPushButton(self.centralwidget)
        self.btnCapFrame.setGeometry(QtCore.QRect(1390, 110, 151, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btnCapFrame.setFont(font)
        self.btnCapFrame.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btnCapFrame.setObjectName("btnCapFrame")
        self.sliderContrast = QtWidgets.QSlider(self.centralwidget)
        self.sliderContrast.setGeometry(QtCore.QRect(1650, 900, 261, 22))
        self.sliderContrast.setFocusPolicy(QtCore.Qt.NoFocus)
        self.sliderContrast.setMinimum(0)
        self.sliderContrast.setMaximum(99)
        self.sliderContrast.setProperty("value", 49)
        self.sliderContrast.setSliderPosition(49)
        self.sliderContrast.setOrientation(QtCore.Qt.Horizontal)
        self.sliderContrast.setObjectName("sliderContrast")
        self.sliderBrightness = QtWidgets.QSlider(self.centralwidget)
        self.sliderBrightness.setGeometry(QtCore.QRect(1650, 850, 261, 22))
        self.sliderBrightness.setFocusPolicy(QtCore.Qt.NoFocus)
        self.sliderBrightness.setMinimum(-100)
        self.sliderBrightness.setMaximum(100)
        self.sliderBrightness.setSliderPosition(0)
        self.sliderBrightness.setOrientation(QtCore.Qt.Horizontal)
        self.sliderBrightness.setObjectName("sliderBrightness")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(1740, 870, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(1740, 920, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.txtDistMeters = QtWidgets.QLabel(self.centralwidget)
        self.txtDistMeters.setGeometry(QtCore.QRect(1560, 10, 221, 101))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(56)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.txtDistMeters.setFont(font)
        self.txtDistMeters.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-color: rgb(0, 0, 0);")
        self.txtDistMeters.setFrameShape(QtWidgets.QFrame.Box)
        self.txtDistMeters.setText("")
        self.txtDistMeters.setObjectName("txtDistMeters")
        self.txtDistFeet = QtWidgets.QLabel(self.centralwidget)
        self.txtDistFeet.setGeometry(QtCore.QRect(1560, 150, 221, 101))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(56)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.txtDistFeet.setFont(font)
        self.txtDistFeet.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-color: rgb(0, 0, 0);")
        self.txtDistFeet.setFrameShape(QtWidgets.QFrame.Box)
        self.txtDistFeet.setText("")
        self.txtDistFeet.setObjectName("txtDistFeet")
        self.grpboxOutcome = QtWidgets.QGroupBox(self.centralwidget)
        self.grpboxOutcome.setGeometry(QtCore.QRect(1800, 10, 111, 121))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.grpboxOutcome.setFont(font)
        self.grpboxOutcome.setObjectName("grpboxOutcome")
        self.radbtnJumpOK = QtWidgets.QRadioButton(self.grpboxOutcome)
        self.radbtnJumpOK.setGeometry(QtCore.QRect(10, 30, 95, 20))
        self.radbtnJumpOK.setFocusPolicy(QtCore.Qt.NoFocus)
        self.radbtnJumpOK.setChecked(True)
        self.radbtnJumpOK.setObjectName("radbtnJumpOK")
        self.radbtnFall = QtWidgets.QRadioButton(self.grpboxOutcome)
        self.radbtnFall.setGeometry(QtCore.QRect(10, 60, 95, 20))
        self.radbtnFall.setFocusPolicy(QtCore.Qt.NoFocus)
        self.radbtnFall.setObjectName("radbtnFall")
        self.radbtnPass = QtWidgets.QRadioButton(self.grpboxOutcome)
        self.radbtnPass.setGeometry(QtCore.QRect(10, 90, 95, 20))
        self.radbtnPass.setFocusPolicy(QtCore.Qt.NoFocus)
        self.radbtnPass.setObjectName("radbtnPass")
        self.grpboxReride = QtWidgets.QGroupBox(self.centralwidget)
        self.grpboxReride.setGeometry(QtCore.QRect(1800, 150, 111, 121))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.grpboxReride.setFont(font)
        self.grpboxReride.setObjectName("grpboxReride")
        self.radbtnNoReride = QtWidgets.QRadioButton(self.grpboxReride)
        self.radbtnNoReride.setGeometry(QtCore.QRect(10, 20, 121, 31))
        self.radbtnNoReride.setFocusPolicy(QtCore.Qt.NoFocus)
        self.radbtnNoReride.setChecked(True)
        self.radbtnNoReride.setObjectName("radbtnNoReride")
        self.radbtnMandatory = QtWidgets.QRadioButton(self.grpboxReride)
        self.radbtnMandatory.setGeometry(QtCore.QRect(10, 50, 111, 31))
        self.radbtnMandatory.setFocusPolicy(QtCore.Qt.NoFocus)
        self.radbtnMandatory.setObjectName("radbtnMandatory")
        self.radbtnOptional = QtWidgets.QRadioButton(self.grpboxReride)
        self.radbtnOptional.setGeometry(QtCore.QRect(10, 80, 111, 31))
        self.radbtnOptional.setFocusPolicy(QtCore.Qt.NoFocus)
        self.radbtnOptional.setObjectName("radbtnOptional")
        self.btnPVR = QtWidgets.QPushButton(self.centralwidget)
        self.btnPVR.setGeometry(QtCore.QRect(20, 830, 111, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btnPVR.setFont(font)
        self.btnPVR.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btnPVR.setStyleSheet("background-color: rgb(255, 148, 75);")
        self.btnPVR.setObjectName("btnPVR")
        self.chkboxShowDistancesMeters = QtWidgets.QCheckBox(self.centralwidget)
        self.chkboxShowDistancesMeters.setGeometry(QtCore.QRect(1020, 898, 251, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.chkboxShowDistancesMeters.setFont(font)
        self.chkboxShowDistancesMeters.setFocusPolicy(QtCore.Qt.NoFocus)
        self.chkboxShowDistancesMeters.setObjectName("chkboxShowDistancesMeters")
        self.txtVerifyMeters = QtWidgets.QLineEdit(self.centralwidget)
        self.txtVerifyMeters.setEnabled(False)
        self.txtVerifyMeters.setGeometry(QtCore.QRect(1840, 738, 61, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtVerifyMeters.sizePolicy().hasHeightForWidth())
        self.txtVerifyMeters.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.txtVerifyMeters.setFont(font)
        self.txtVerifyMeters.setFocusPolicy(QtCore.Qt.NoFocus)
        self.txtVerifyMeters.setAlignment(QtCore.Qt.AlignCenter)
        self.txtVerifyMeters.setReadOnly(False)
        self.txtVerifyMeters.setObjectName("txtVerifyMeters")
        self.txtVerifyFeet = QtWidgets.QLineEdit(self.centralwidget)
        self.txtVerifyFeet.setEnabled(False)
        self.txtVerifyFeet.setGeometry(QtCore.QRect(1840, 778, 61, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtVerifyFeet.sizePolicy().hasHeightForWidth())
        self.txtVerifyFeet.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.txtVerifyFeet.setFont(font)
        self.txtVerifyFeet.setFocusPolicy(QtCore.Qt.NoFocus)
        self.txtVerifyFeet.setAlignment(QtCore.Qt.AlignCenter)
        self.txtVerifyFeet.setReadOnly(False)
        self.txtVerifyFeet.setObjectName("txtVerifyFeet")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(1855, 812, 41, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_33 = QtWidgets.QLabel(self.centralwidget)
        self.label_33.setGeometry(QtCore.QRect(1815, 748, 31, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_33.setFont(font)
        self.label_33.setAlignment(QtCore.Qt.AlignCenter)
        self.label_33.setObjectName("label_33")
        self.label_34 = QtWidgets.QLabel(self.centralwidget)
        self.label_34.setGeometry(QtCore.QRect(1815, 787, 31, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_34.setFont(font)
        self.label_34.setAlignment(QtCore.Qt.AlignCenter)
        self.label_34.setObjectName("label_34")
        self.lblGrids = QtWidgets.QLabel(self.centralwidget)
        self.lblGrids.setGeometry(QtCore.QRect(20, 913, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lblGrids.setFont(font)
        self.lblGrids.setObjectName("lblGrids")
        self.txtGrid1 = QtWidgets.QLineEdit(self.centralwidget)
        self.txtGrid1.setGeometry(QtCore.QRect(95, 910, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.txtGrid1.setFont(font)
        self.txtGrid1.setFocusPolicy(QtCore.Qt.NoFocus)
        self.txtGrid1.setReadOnly(True)
        self.txtGrid1.setObjectName("txtGrid1")
        self.txtGrid2 = QtWidgets.QLineEdit(self.centralwidget)
        self.txtGrid2.setGeometry(QtCore.QRect(329, 910, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.txtGrid2.setFont(font)
        self.txtGrid2.setFocusPolicy(QtCore.Qt.NoFocus)
        self.txtGrid2.setReadOnly(True)
        self.txtGrid2.setObjectName("txtGrid2")
        self.txtGrid3 = QtWidgets.QLineEdit(self.centralwidget)
        self.txtGrid3.setGeometry(QtCore.QRect(558, 910, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.txtGrid3.setFont(font)
        self.txtGrid3.setFocusPolicy(QtCore.Qt.NoFocus)
        self.txtGrid3.setReadOnly(True)
        self.txtGrid3.setObjectName("txtGrid3")
        self.txtGrid4 = QtWidgets.QLineEdit(self.centralwidget)
        self.txtGrid4.setGeometry(QtCore.QRect(800, 910, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.txtGrid4.setFont(font)
        self.txtGrid4.setFocusPolicy(QtCore.Qt.NoFocus)
        self.txtGrid4.setReadOnly(True)
        self.txtGrid4.setObjectName("txtGrid4")
        self.lblGrids2 = QtWidgets.QLabel(self.centralwidget)
        self.lblGrids2.setGeometry(QtCore.QRect(302, 915, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lblGrids2.setFont(font)
        self.lblGrids2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblGrids2.setObjectName("lblGrids2")
        self.lblGrids3 = QtWidgets.QLabel(self.centralwidget)
        self.lblGrids3.setGeometry(QtCore.QRect(533, 915, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lblGrids3.setFont(font)
        self.lblGrids3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblGrids3.setObjectName("lblGrids3")
        self.lblGrids4 = QtWidgets.QLabel(self.centralwidget)
        self.lblGrids4.setGeometry(QtCore.QRect(765, 916, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lblGrids4.setFont(font)
        self.lblGrids4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblGrids4.setObjectName("lblGrids4")
        self.btnGrid = QtWidgets.QPushButton(self.centralwidget)
        self.btnGrid.setGeometry(QtCore.QRect(1380, 560, 111, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btnGrid.setFont(font)
        self.btnGrid.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.btnGrid.setStyleSheet("background-color: #fef29a;")
        self.btnGrid.setObjectName("btnGrid")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(1650, 590, 120, 80))
        self.groupBox.setStyleSheet("border: None;")
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.radbtnSurvey = QtWidgets.QRadioButton(self.groupBox)
        self.radbtnSurvey.setGeometry(QtCore.QRect(20, 16, 95, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.radbtnSurvey.setFont(font)
        self.radbtnSurvey.setFocusPolicy(QtCore.Qt.NoFocus)
        self.radbtnSurvey.setChecked(True)
        self.radbtnSurvey.setObjectName("radbtnSurvey")
        self.radbtnScreen = QtWidgets.QRadioButton(self.groupBox)
        self.radbtnScreen.setGeometry(QtCore.QRect(20, 51, 95, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.radbtnScreen.setFont(font)
        self.radbtnScreen.setFocusPolicy(QtCore.Qt.NoFocus)
        self.radbtnScreen.setObjectName("radbtnScreen")
        self.chkboxShowDistancesFeet = QtWidgets.QCheckBox(self.centralwidget)
        self.chkboxShowDistancesFeet.setGeometry(QtCore.QRect(1020, 926, 241, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.chkboxShowDistancesFeet.setFont(font)
        self.chkboxShowDistancesFeet.setFocusPolicy(QtCore.Qt.NoFocus)
        self.chkboxShowDistancesFeet.setObjectName("chkboxShowDistancesFeet")
        self.lblWSC = QtWidgets.QLabel(self.centralwidget)
        self.lblWSC.setGeometry(QtCore.QRect(1410, 470, 63, 64))
        self.lblWSC.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lblWSC.setText("")
        self.lblWSC.setObjectName("lblWSC")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1999, 26))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuNames = QtWidgets.QMenu(self.menubar)
        self.menuNames.setObjectName("menuNames")
        self.menuInfo = QtWidgets.QMenu(self.menubar)
        self.menuInfo.setObjectName("menuInfo")
        self.menuLoad_Grid = QtWidgets.QMenu(self.menubar)
        self.menuLoad_Grid.setObjectName("menuLoad_Grid")
        self.menuDisplay = QtWidgets.QMenu(self.menubar)
        self.menuDisplay.setObjectName("menuDisplay")
        self.menuEnable_Distance_Display = QtWidgets.QMenu(self.menuDisplay)
        self.menuEnable_Distance_Display.setObjectName("menuEnable_Distance_Display")
        self.menuWaterSkiConnect = QtWidgets.QMenu(self.menubar)
        self.menuWaterSkiConnect.setObjectName("menuWaterSkiConnect")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpenSavedVideo = QtWidgets.QAction(MainWindow)
        self.actionOpenSavedVideo.setObjectName("actionOpenSavedVideo")
        self.actionManual = QtWidgets.QAction(MainWindow)
        self.actionManual.setObjectName("actionManual")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionLicense = QtWidgets.QAction(MainWindow)
        self.actionLicense.setObjectName("actionLicense")
        self.actionImport_Names = QtWidgets.QAction(MainWindow)
        self.actionImport_Names.setObjectName("actionImport_Names")
        self.actionLoad_Grid = QtWidgets.QAction(MainWindow)
        self.actionLoad_Grid.setObjectName("actionLoad_Grid")
        self.actionSave_Grid = QtWidgets.QAction(MainWindow)
        self.actionSave_Grid.setObjectName("actionSave_Grid")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionConfigurations = QtWidgets.QAction(MainWindow)
        self.actionConfigurations.setObjectName("actionConfigurations")
        self.actionSaveGrid = QtWidgets.QAction(MainWindow)
        self.actionSaveGrid.setEnabled(True)
        self.actionSaveGrid.setObjectName("actionSaveGrid")
        self.actionGrid_3 = QtWidgets.QAction(MainWindow)
        self.actionGrid_3.setEnabled(False)
        self.actionGrid_3.setObjectName("actionGrid_3")
        self.actionGrid_4 = QtWidgets.QAction(MainWindow)
        self.actionGrid_4.setEnabled(False)
        self.actionGrid_4.setObjectName("actionGrid_4")
        self.actionGrid1 = QtWidgets.QAction(MainWindow)
        self.actionGrid1.setObjectName("actionGrid1")
        self.actionGrid_5 = QtWidgets.QAction(MainWindow)
        self.actionGrid_5.setObjectName("actionGrid_5")
        self.actiongrid_3 = QtWidgets.QAction(MainWindow)
        self.actiongrid_3.setObjectName("actiongrid_3")
        self.actionGrid_6 = QtWidgets.QAction(MainWindow)
        self.actionGrid_6.setObjectName("actionGrid_6")
        self.actionLoadGrid1 = QtWidgets.QAction(MainWindow)
        self.actionLoadGrid1.setObjectName("actionLoadGrid1")
        self.actionLoadGrid2 = QtWidgets.QAction(MainWindow)
        self.actionLoadGrid2.setEnabled(False)
        self.actionLoadGrid2.setObjectName("actionLoadGrid2")
        self.actionLoadGrid3 = QtWidgets.QAction(MainWindow)
        self.actionLoadGrid3.setEnabled(False)
        self.actionLoadGrid3.setObjectName("actionLoadGrid3")
        self.actionLoadGrid4 = QtWidgets.QAction(MainWindow)
        self.actionLoadGrid4.setEnabled(False)
        self.actionLoadGrid4.setObjectName("actionLoadGrid4")
        self.actionOpenSavedFrame = QtWidgets.QAction(MainWindow)
        self.actionOpenSavedFrame.setObjectName("actionOpenSavedFrame")
        self.actionLoadGrid = QtWidgets.QAction(MainWindow)
        self.actionLoadGrid.setObjectName("actionLoadGrid")
        self.actionClearSkierList = QtWidgets.QAction(MainWindow)
        self.actionClearSkierList.setObjectName("actionClearSkierList")
        self.actionDisableDistDisplay = QtWidgets.QAction(MainWindow)
        self.actionDisableDistDisplay.setObjectName("actionDisableDistDisplay")
        self.actionFlashMob = QtWidgets.QAction(MainWindow)
        self.actionFlashMob.setObjectName("actionFlashMob")
        self.actionPeasInAPod = QtWidgets.QAction(MainWindow)
        self.actionPeasInAPod.setObjectName("actionPeasInAPod")
        self.actionMeterORama = QtWidgets.QAction(MainWindow)
        self.actionMeterORama.setObjectName("actionMeterORama")
        self.actionBigfoot = QtWidgets.QAction(MainWindow)
        self.actionBigfoot.setObjectName("actionBigfoot")
        self.actionHistory = QtWidgets.QAction(MainWindow)
        self.actionHistory.setObjectName("actionHistory")
        self.actionConnect = QtWidgets.QAction(MainWindow)
        self.actionConnect.setObjectName("actionConnect")
        self.actionDisconnect = QtWidgets.QAction(MainWindow)
        self.actionDisconnect.setObjectName("actionDisconnect")
        self.actionShowPIN = QtWidgets.QAction(MainWindow)
        self.actionShowPIN.setObjectName("actionShowPIN")
        self.menuFile.addAction(self.actionOpenSavedVideo)
        self.menuFile.addAction(self.actionOpenSavedFrame)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionConfigurations)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuNames.addAction(self.actionImport_Names)
        self.menuNames.addAction(self.actionClearSkierList)
        self.menuInfo.addAction(self.actionManual)
        self.menuInfo.addAction(self.actionLicense)
        self.menuInfo.addAction(self.actionHistory)
        self.menuInfo.addAction(self.actionAbout)
        self.menuLoad_Grid.addAction(self.actionSaveGrid)
        self.menuLoad_Grid.addAction(self.actionLoadGrid)
        self.menuEnable_Distance_Display.addAction(self.actionFlashMob)
        self.menuEnable_Distance_Display.addAction(self.actionPeasInAPod)
        self.menuEnable_Distance_Display.addAction(self.actionMeterORama)
        self.menuEnable_Distance_Display.addAction(self.actionBigfoot)
        self.menuDisplay.addAction(self.menuEnable_Distance_Display.menuAction())
        self.menuDisplay.addAction(self.actionDisableDistDisplay)
        self.menuWaterSkiConnect.addAction(self.actionConnect)
        self.menuWaterSkiConnect.addAction(self.actionDisconnect)
        self.menuWaterSkiConnect.addAction(self.actionShowPIN)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuNames.menuAction())
        self.menubar.addAction(self.menuLoad_Grid.menuAction())
        self.menubar.addAction(self.menuDisplay.menuAction())
        self.menubar.addAction(self.menuWaterSkiConnect.menuAction())
        self.menubar.addAction(self.menuInfo.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.btnHitRamp, self.btnGrid)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Video Tape Measure"))
        self.lblSurveyULY.setText(_translate("MainWindow", "Y"))
        self.lblSurveyULX.setText(_translate("MainWindow", "X"))
        self.txtSurveyULY.setText(_translate("MainWindow", "0.00"))
        self.txtSurveyULX.setText(_translate("MainWindow", "0.00"))
        self.lblSurveyURY.setText(_translate("MainWindow", "Y"))
        self.txtSurveyURY.setText(_translate("MainWindow", "0.00"))
        self.txtSurveyURX.setText(_translate("MainWindow", "0.00"))
        self.lblSurveyURX.setText(_translate("MainWindow", "X"))
        self.lblSurveyLLY.setText(_translate("MainWindow", "Y"))
        self.txtSurveyLLY.setText(_translate("MainWindow", "0.00"))
        self.txtSurveyLLX.setText(_translate("MainWindow", "0.00"))
        self.lblSurveyLLX.setText(_translate("MainWindow", "X"))
        self.txtSurveyLRX.setText(_translate("MainWindow", "0.00"))
        self.lblSurveyLRY.setText(_translate("MainWindow", "Y"))
        self.txtSurveyLRY.setText(_translate("MainWindow", "0.00"))
        self.lblSurveyLRX.setText(_translate("MainWindow", "X"))
        self.lblSurveyJpX.setText(_translate("MainWindow", "X"))
        self.txtSurveyRpY.setText(_translate("MainWindow", "0.00"))
        self.lblRamp.setText(_translate("MainWindow", "Ramp"))
        self.txtSurveyRpX.setText(_translate("MainWindow", "0.00"))
        self.lblSurveyJpY.setText(_translate("MainWindow", "Y"))
        self.lblSurveyCkX.setText(_translate("MainWindow", "X"))
        self.lblSurveyCkY.setText(_translate("MainWindow", "Y"))
        self.txtSurveyCkY.setText(_translate("MainWindow", "0.00"))
        self.txtSurveyCkX.setText(_translate("MainWindow", "0.00"))
        self.btnHitRamp.setText(_translate("MainWindow", "Skier Hits Ramp"))
        self.cboxSkierNames.setCurrentText(_translate("MainWindow", "Jump Skier"))
        self.lblSkierName.setText(_translate("MainWindow", "Skier Name"))
        self.lblJump.setText(_translate("MainWindow", "Jump"))
        self.lblRound.setText(_translate("MainWindow", "Round"))
        self.btnNextJump.setText(_translate("MainWindow", "Next Jump"))
        self.chkboxShowBuoys.setText(_translate("MainWindow", "Show Buoy Markers"))
        self.chkboxShowHomoLevel.setText(_translate("MainWindow", "Show Homologation Level"))
        self.radbtnUL.setText(_translate("MainWindow", "Upper Left"))
        self.radbtnUR.setText(_translate("MainWindow", "Upper Right"))
        self.radbtnLL.setText(_translate("MainWindow", "Lower Left"))
        self.radbtnLR.setText(_translate("MainWindow", "Lower Right"))
        self.radbtnCheck.setText(_translate("MainWindow", "Check Buoy"))
        self.chkboxLockGridBuoys.setText(_translate("MainWindow", "Lock Grid"))
        self.btnCheck.setText(_translate("MainWindow", "Check"))
        self.label_30.setText(_translate("MainWindow", "Y"))
        self.txtImg2GrdX.setText(_translate("MainWindow", "00.00"))
        self.txtImg2GrdY.setText(_translate("MainWindow", "00.00"))
        self.label_28.setText(_translate("MainWindow", "X"))
        self.chkboxVerify.setText(_translate("MainWindow", "Verify"))
        self.verifyLabel.setText(_translate("MainWindow", "Click to Verify"))
        self.label.setText(_translate("MainWindow", "Screen"))
        self.label_2.setText(_translate("MainWindow", "Ground"))
        self.txtVerifyScreenX.setText(_translate("MainWindow", "0"))
        self.label_31.setText(_translate("MainWindow", "Y"))
        self.label_32.setText(_translate("MainWindow", "X"))
        self.txtVerifyScreenY.setText(_translate("MainWindow", "0"))
        self.chkboxSetup.setText(_translate("MainWindow", "Setup Grid"))
        self.grpboxLoupe.setTitle(_translate("MainWindow", "Loupe"))
        self.radbtn4x.setText(_translate("MainWindow", "4x"))
        self.radbtn3x.setText(_translate("MainWindow", "3x"))
        self.radbtn5x.setText(_translate("MainWindow", "5x"))
        self.radbtn2x.setText(_translate("MainWindow", "2x"))
        self.btnClickDown.setText(_translate("MainWindow", "q"))
        self.btnClickRight.setText(_translate("MainWindow", "u"))
        self.btnClickLeft.setText(_translate("MainWindow", "t"))
        self.btnClickUp.setText(_translate("MainWindow", "p"))
        self.btnReselectFrame.setText(_translate("MainWindow", "Reselect Frame"))
        self.lblMeters.setText(_translate("MainWindow", "Meters"))
        self.lblFeet.setText(_translate("MainWindow", "Feet"))
        self.label_3.setText(_translate("MainWindow", "Must press  ENTER key to complete typing a new name"))
        self.chkboxShowGridAccuracy.setText(_translate("MainWindow", "Show Grid Accuracy"))
        self.btnCapFrame.setText(_translate("MainWindow", "Capture Frame"))
        self.label_4.setText(_translate("MainWindow", "Brightness"))
        self.label_5.setText(_translate("MainWindow", "Contrast"))
        self.grpboxOutcome.setTitle(_translate("MainWindow", "Outcome"))
        self.radbtnJumpOK.setText(_translate("MainWindow", "Jump OK"))
        self.radbtnFall.setText(_translate("MainWindow", "Fall"))
        self.radbtnPass.setText(_translate("MainWindow", "Pass"))
        self.grpboxReride.setTitle(_translate("MainWindow", "Reride"))
        self.radbtnNoReride.setText(_translate("MainWindow", "No Reride"))
        self.radbtnMandatory.setText(_translate("MainWindow", "Mandatory"))
        self.radbtnOptional.setText(_translate("MainWindow", "Optional"))
        self.btnPVR.setText(_translate("MainWindow", "PVR"))
        self.chkboxShowDistancesMeters.setText(_translate("MainWindow", "Show Distances (meters)"))
        self.txtVerifyMeters.setText(_translate("MainWindow", "0.0"))
        self.txtVerifyFeet.setText(_translate("MainWindow", "0"))
        self.label_6.setText(_translate("MainWindow", "Dist"))
        self.label_33.setText(_translate("MainWindow", "m"))
        self.label_34.setText(_translate("MainWindow", "ft"))
        self.lblGrids.setText(_translate("MainWindow", "Grids: 1"))
        self.lblGrids2.setText(_translate("MainWindow", "2"))
        self.lblGrids3.setText(_translate("MainWindow", "3"))
        self.lblGrids4.setText(_translate("MainWindow", "4"))
        self.btnGrid.setText(_translate("MainWindow", "Grid  1"))
        self.radbtnSurvey.setText(_translate("MainWindow", "Survey"))
        self.radbtnScreen.setText(_translate("MainWindow", "Screen"))
        self.chkboxShowDistancesFeet.setText(_translate("MainWindow", "Show Distances (feet)"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuNames.setTitle(_translate("MainWindow", "Names"))
        self.menuInfo.setTitle(_translate("MainWindow", "Info"))
        self.menuLoad_Grid.setTitle(_translate("MainWindow", "Grids"))
        self.menuDisplay.setTitle(_translate("MainWindow", "Display"))
        self.menuEnable_Distance_Display.setTitle(_translate("MainWindow", "Enable Distance Display"))
        self.menuWaterSkiConnect.setTitle(_translate("MainWindow", "WaterSkiConnect"))
        self.actionOpenSavedVideo.setText(_translate("MainWindow", "Open Saved Video"))
        self.actionManual.setText(_translate("MainWindow", "Manual"))
        self.actionAbout.setText(_translate("MainWindow", "About..."))
        self.actionLicense.setText(_translate("MainWindow", "License"))
        self.actionImport_Names.setText(_translate("MainWindow", "Import Names"))
        self.actionLoad_Grid.setText(_translate("MainWindow", "Load Grid"))
        self.actionSave_Grid.setText(_translate("MainWindow", "Save Grid"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionConfigurations.setText(_translate("MainWindow", "Configurations..."))
        self.actionSaveGrid.setText(_translate("MainWindow", "Save Grid"))
        self.actionGrid_3.setText(_translate("MainWindow", "Grid 3"))
        self.actionGrid_4.setText(_translate("MainWindow", "Grid 4"))
        self.actionGrid1.setText(_translate("MainWindow", "Grid1"))
        self.actionGrid_5.setText(_translate("MainWindow", "Grid 2"))
        self.actiongrid_3.setText(_translate("MainWindow", "Grid 3"))
        self.actionGrid_6.setText(_translate("MainWindow", "Grid 4"))
        self.actionLoadGrid1.setText(_translate("MainWindow", "Grid 1"))
        self.actionLoadGrid2.setText(_translate("MainWindow", "Grid 2"))
        self.actionLoadGrid3.setText(_translate("MainWindow", "Grid 3"))
        self.actionLoadGrid4.setText(_translate("MainWindow", "Grid 4"))
        self.actionOpenSavedFrame.setText(_translate("MainWindow", "Open Saved Frame"))
        self.actionLoadGrid.setText(_translate("MainWindow", "Load Grid"))
        self.actionClearSkierList.setText(_translate("MainWindow", "Clear Skier List"))
        self.actionDisableDistDisplay.setText(_translate("MainWindow", "Disable Distance Display"))
        self.actionFlashMob.setText(_translate("MainWindow", "Flash Mob"))
        self.actionPeasInAPod.setText(_translate("MainWindow", "Two Peas in a Pod"))
        self.actionMeterORama.setText(_translate("MainWindow", "Meter-O-Rama"))
        self.actionBigfoot.setText(_translate("MainWindow", "Bigfoot"))
        self.actionHistory.setText(_translate("MainWindow", "History"))
        self.actionConnect.setText(_translate("MainWindow", "Connect"))
        self.actionDisconnect.setText(_translate("MainWindow", "Disconnect"))
        self.actionShowPIN.setText(_translate("MainWindow", "Show PIN"))
from CustomCombo import CustomCombo


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
